WebApplicationMVCTanisma/Models/Ogrenci.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplicationMVCTanisma.Models
{
    public class Ogrenci : IEquatable<Ogrenci>
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Öğrenci adı boş geçilemez!")]
        [StringLength(maximumLength:25,MinimumLength =2,ErrorMessage ="Adınız 2 ile 25 karakter aralığında olmalıdır!")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Öğrenci soyadı boş geçilemez!")]
        [StringLength(maximumLength: 25, MinimumLength = 2, ErrorMessage = "Soyadınız 2 ile 25 karakter aralığında olmalıdır!")]
        public string Soyad { get; set; }
        public DateTime? DogumTarihi { get; set; }
        public static List<Ogrenci> OgrenciListesi { get; set; } = new List<Ogrenci>();
        public static List<Ogrenci> OgrencileriGetir()
        {
            if (OgrenciListesi.Count == 0)
            {
                OgrenciListesi = new List<Ogrenci>()
                {
                    new Ogrenci(){Id=1,Ad="Umut",Soyad="Yılmaz",DogumTarihi=new DateTime(1996,09,16)},
                    new Ogrenci(){Id=2,Ad="Berkan",Soyad="Çalasın",DogumTarihi=new DateTime(1997,08,13)},
                    new Ogrenci(){Id=3,Ad="Gökhan",Soyad="Oral",DogumTarihi=new DateTime(1997,08,11)}
                };
            }


            return OgrenciListesi;
            ;
        }
        public bool Equals(Ogrenci other)
        {
            return Id == other.Id;
        }
    }
}

WebApplicationMVCTanisma/Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationMVCTanisma.Models;

namespace WebApplicationMVCTanisma.Controllers
{
    public class OgrenciController : Controller
    {
        // GET: Ogrenci
        public ActionResult Listele()
        {
            List<Ogrenci> ogrList = Ogrenci.OgrencileriGetir();
            return View(ogrList);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Ogrenci ogr)
        {
            //Veritabanımız olmadığı için id'yi kendimiz atama amaçlı bu satırları yazdık
            var tumOgrler = Ogrenci.OgrencileriGetir();
            ogr.Id = tumOgrler.Count + 1;
            //öğrenci ekleyelim
            Ogrenci.OgrenciListesi.Add(ogr);

            //Ekleme yapıldıktan sonra Listele Action'ına redirect olalım.
            return RedirectToAction("Listele");
        }
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            if (id > 0)
            {
                Ogrenci bulunanOgr = Ogrenci.OgrenciListesi.FirstOrDefault(x => x.Id == id);
                return View(bulunanOgr);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Guncelle(Ogrenci ogr)
        {
            Ogrenci guncellenecekEskiOgr = Ogrenci.OgrenciListesi.FirstOrDefault(x => x.Id == ogr.Id);
            if (guncellenecekEskiOgr!=null)
            {
                //Öğrenciyi buldun. Bulduğun bu öğrenciye yeni değerler ata
                //guncellenecekEskiOgr.Ad=ogr.Ad;
                //=işaretinin sağında Güncelle sayfasına girdiğimiz bilgiyi aldık ve bizdeki mevcut öğrenciye atadık
                guncellenecekEskiOgr.Ad = ogr.Ad;
                guncellenecekEskiOgr.Soyad = ogr.Soyad;
                guncellenecekEskiOgr.DogumTarihi = ogr.DogumTarihi;
            }

            return RedirectToAction("Listele");
        }

        [HttpGet]
        public ActionResult Sil(int id)
        {
            var silinecekOgr = Ogrenci.OgrenciListesi.FirstOrDefault(x => x.Id == id);
            return View(silinecekOgr);
        }
        [HttpPost]
        public ActionResult Sil(Ogrenci ogr)
        {
            if (ogr.Id>0)
            {
                Ogrenci.OgrenciListesi.Remove(ogr);
            }
            return RedirectToAction("Listele");
        }
        [HttpPost]
        public ActionResult Sil2(Ogrenci ogr)
        {
            if (ogr.Id > 0)
            {
                Ogrenci.OgrenciListesi.Remove(ogr);
                return Json(new { success = true });
            }
            return Json(new { success = false,error= "Beklenmedik hata oldu.Silinemedi!" });
        }
    }
}

WebApplicationMVCTanisma/Views/Ogrenci/Ekle.cshtml
@using WebApplicationMVCTanisma.Models;
@{
    ViewBag.Title = "Ekle";
}

<h2>Yeni Öğrenci Ekleyelim</h2>
<form action="Ekle" method="post">
    <label>Öğrenci Adı:</label>
    <input type="text" placeholder="Ad Giriniz..." name="Ad" class="form-control" /><br />
    <label>Öğrenci Soyadı:</label>
    <input type="text" placeholder="Soyad Giriniz..." name="Soyad" class="form-control" /><br />
    <label>Doğum Tarihi:</label>
    <input type="date" name="DogumTarihi" class="form-control"/><br />
    <input type="submit" value="EKLE" class="btn btn-primary" />
    <a href="/Ogrenci/Listele" class="btn btn-default" style="background-color:dimgray;color:white">Listeye Geri Dön</a>
</form>


@{ 
    
}

WebApplicationMVCTanisma/Views/Ogrenci/Guncelle.cshtml
@using WebApplicationMVCTanisma.Models
@model Ogrenci
@{
    ViewBag.Title = "Guncelle";
}

<h2>Öğrenciyi Güncelle</h2>
<br />

@*<form action="Guncelle" method="post">
        <label>Ad</label>
        <input type="text" name="Ad" value="@Model.Ad" class="form-control" /> <br />
        <label>Soyad</label>
        <input  type="text" name="Soyad" value="@Model.Soyad" class="form-control" /> <br />
        <label>Doğum Tarihi</label>
        <input type="datetime"  name="DogumTarihi" value="@Model.DogumTarihi"  class="form-control" />
        <br />
        <input type="hidden" name="Id"  value="@Model.Id" />
        <input type="submit" class="btn btn-primary" value="Güncelle" />
    </form>*@


@using (Html.BeginForm("Guncelle", "Ogrenci", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)
    @Html.Label("Ad")
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Soyad)
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    <label>Doğum Tarihi:</label>
    @Html.TextBoxFor(x => x.DogumTarihi, new { @class = "form-control" })
    <br />
    @*@Html.ActionLink("Güncelle", "Guncelle", "Ogrenci",
        new { }, new { @class = "btn btn-primary" })*@
    <input type="submit" class="btn btn-primary" value="Güncelle" />
    <a href="/Ogrenci/Listele" class="btn btn-default" style="background-color:dimgray;color:white">Listeye Geri Dön</a>
}

WebApplicationMVCTanisma/Views/Ogrenci/Listele.cshtml
@using WebApplicationMVCTanisma.Models;

@{
    ViewBag.Title = "Listele";
}
@{
    int siraNo = 1;
}
<h2>Tüm Öğrenciler</h2>
<br />

<table class="table table-hover">
    <tr>
        <th style="text-align:center">Sıra No</th>
        <th style="text-align:center">Ad</th>
        <th style="text-align:center">Soyad</th>
        <th style="text-align:center">Doğum Tarihi</th>
        <th style="text-align:center">Güncelleme İşlemi</th>
        <th style="text-align:center">Silme İşlemi</th>
    </tr>
    @foreach (Ogrenci item in Model)
    {
        <tr style="text-align:center">
            <td>@(siraNo++)</td>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.DogumTarihi</td>
            <td>
                @*<a href="Guncelle/@item.Id" class="btn btn-warning">Güncelle</a>*@
                @Html.ActionLink("Güncelle", "Guncelle", "Ogrenci", new { id = item.Id }, new { @class = "btn btn-warning" })
            </td>
            <td>
                @*<a href="Sil/@item.Id" class="btn btn-danger">Sil</a>*@ @*Eşdeğer*@
                @Html.ActionLink("Sil", "Sil", "Ogrenci", new { id = item.Id }, new { @class = "btn btn-danger" })
                <input type="button" value="Sil" class="btn btn-default" style="background-color:pink" onclick="ConfirmDelete(@item.Id)"/>
            </td>
        </tr>

    }

</table>
<br />

<a href="/Ogrenci/Ekle" class="btn btn-success">Yeni Öğrenci Ekle</a>

<script type="text/JavaScript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript">
    function ConfirmDelete(id) {
        var x = confirm("Silmek istediğinize emin misiniz?");
        if (x) {
            $.ajax({
                type: "Post",
                url: "/Ogrenci/Sil2/"+id,
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (response) {
                    //alert(response.status);
                    alert('Silindi');
                    window.location.href = "/Ogrenci/Listele";
                },
                error: function () {
                    alert('Beklenmedik hata oldu.Silinemedi!');
                }
            });
        }
    }
</script>

WebApplicationMVCTanisma/Views/Ogrenci/Sil.cshtml
@using WebApplicationMVCTanisma.Models
@model Ogrenci
@{
    ViewBag.Title = "Sil";
}

<h4>Öğrenci Bilgileri</h4>
<br />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(x => x.Ad)
    </dt>
    <dd>
        @Html.DisplayFor(x => x.Ad)
    </dd>
    <dt>
        @Html.DisplayNameFor(x => x.Soyad)
    </dt>
    <dd>
        @Html.DisplayFor(x => x.Soyad)
    </dd>
</dl> <br />

@*@Html.HiddenFor(x=>x.Id)*@
<input type="hidden" name="@Model.Id" />

@using (Html.BeginForm("Sil","Ogrenci",FormMethod.Post)) {
<div class="form-actions no-color">
    <input type="submit" value="Sil" class="btn btn-danger" />
    <a href="/Ogrenci/Listele" class="btn btn-default" style="background-color:dimgray;color:white">Listeye Geri Dön</a>
</div>
}